### ISSUE TITLE
Just MAC-Address does not work

### ISSUE THREAD

**Issue by modmax** [frankjoke/ioBroker.radar#14] opened 2017-10-24 17:40 UTC
In order to check the presence of mobile phones I added some entries with justr a MAC-Adress.
When storing the entry no error occures. But in the log is a warning for an invalid address which says,
that IP or BT address must be given. MAC-Address standalone does not work.
Also no states are created for entries with just MAC address.

Workaround ist to enter "any" in teh IP address field, so that the presence detection works.

**Comment by frankjoke** [comment] 2017-10-24 19:02
Hi Modmax!
The reason is that users which are not on Linux or do not have installed arp-scan cannot use the adapter without any ip address.

The good side is that the IP does not need to be a fixed one, it can also be the name on the network if the devices receives different IP's over time. So just enter the device name.

The problem is that that the mac address can be only verified when you have been successfully sent a package but to send one you need the IP address. If the ip address is not the x.x.x.x then radar looks up on the dns server (usually your router) to get the IP for this name. Without IP or name it cannot send any ping.

**Comment by modmax** [comment] 2017-10-24 20:00
Okay ... I unterstand.
Then the adapter description should be changed, that IP or BT address must be filled; now
there also MAC can be given standalone. According to the description on the adapter config page.

**Comment by frankjoke** [comment] 2017-10-24 20:02
Okay, will do it in next revision and close now the issue.

**Closed by frankjoke** 2017-10-24 20:02 UTC
